### ISSUE TITLE
Unexpected key error on .asf.yaml

### ISSUE THREAD

**Issue by jongyoul** [apache/infrastructure-asfyaml#61]
Hello, I got an error message like:

```
Title: zeppelin-site.git: Error while running publish feature from asf-staging:.asf.yaml

An error occurred while processing the publish feature in .asf.yaml:

while parsing a mapping
unexpected key not in schema 'profile'
  in "zeppelin-site.git/.asf.yaml::publish", line 1, column 1:
    profile: '~'
     ^ (line: 1)

---
With regards, ASF Infra.
For further information, please see the .asf.yaml documentation at:
https://github.com/apache/infrastructure-asfyaml/blob/main/README.md
```

I saw it's already fixed, but I got the same error. Could you please check it?

**Comment by Humbedooh** [comment]
You can't use profiles for website publishing, only for staging.
A staging profile of "foo" would stage your website at zeppelin-foo.staged.apache.org for instance.
Publishing can only ever happen to zeppelin.apache.org, so the profile directive is invalid there. Just remove it from the publish section and it'll work.

**Comment by jongyoul** [comment]
@Humbedooh the .asf.yaml looks like:

```
github:
  homepage: https://zeppelin.apache.org

notifications:
  commits: commits@zeppelin.apache.org
  issues: reviews@zeppelin.apache.org
  pullrequests: reviews@zeppelin.apache.org
  jira_options: link label

jekyll:
  whoami: master
  target: asf-staging

staging:
  profile: ~
  whoami:  asf-staging
```

I didn't use a profile for publish.
