### ISSUE TITLE
Add support for YAML references

### ISSUE THREAD

**Issue by ppkarwasz** [apache/infrastructure-asfyaml#63]
When configuring exactly the same branch protection rules for multiple branches, it would be useful to use YAML anchor and references, for example:

```yaml
# Enforce Review-then-Commit
protected_branches:
  2.x: &default_protection
    # All commits must be signed
    required_signatures: true
    # All reviews must be addressed before merging
    required_conversation_resolution: true
    # Require checks to pass before merging
    required_status_checks:
      checks:
        # The GitHub Actions app: 15368
        - app_id: 15368
          context: "build"
        - app_id: 15368
          context: "codeql-analysis"
    # At least one positive review must be present
    required_pull_request_reviews:
      required_approving_review_count: 1
  main: *default_protection
```

As far as I know `strictyaml` does not allow this feature for security reasons.
In this case an alternative might be allowing to specify the name of the branch that has an identical configuration:

```yaml
# Enforce Review-then-Commit
protected_branches:
  2.x:
    # All commits must be signed
    required_signatures: true
    # All reviews must be addressed before merging
    required_conversation_resolution: true
    # Require checks to pass before merging
    required_status_checks:
      checks:
        # The GitHub Actions app: 15368
        - app_id: 15368
          context: "build"
        - app_id: 15368
          context: "codeql-analysis"
    # At least one positive review must be present
    required_pull_request_reviews:
      required_approving_review_count: 1
  main: "2.x"
```

**Comment by netomi** [comment]
The reason node anchors are not supported in strictyaml sounds more opinionated rather than being a security concern:

https://hitchdev.com/strictyaml/why/node-anchors-and-references-removed/

> While the intent of the feature is obvious (it lets you deduplicate code), the effect is to make the markup more or less unreadable to non-programmers.

**Comment by netomi** [comment]
We could model it like that:

```
# Enforce Review-then-Commit
protected_branches:
  2.x:
    # All commits must be signed
    required_signatures: true
    # All reviews must be addressed before merging
    required_conversation_resolution: true
    # Require checks to pass before merging
    required_status_checks:
      checks:
        # The GitHub Actions app: 15368
        - app_id: 15368
          context: "build"
        - app_id: 15368
          context: "codeql-analysis"
    # At least one positive review must be present
    required_pull_request_reviews:
      required_approving_review_count: 1
  main:
    from: "2.x"
    with:
      required_pull_request_reviews:
        required_approving_review_count: 0
```
